apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: killiankopp/k8s-pod-workstation:latest
            command: ["/bin/bash", "-c", "mkdir -p /root/.ssh && cp /tmp/ssh/id_rsa /root/.ssh/id_rsa && cp /tmp/ssh/id_rsa.pub /root/.ssh/id_rsa.pub && cp /tmp/ssh/known_hosts /root/.ssh/known_hosts && chmod 400 /root/.ssh/id_rsa && chmod 400 /root/.ssh/id_rsa.pub && chmod 400 /root/.ssh/known_hosts && /mnt/save-apache01/save.sh"]
            volumeMounts:
            - mountPath: /mnt/save-apache01
              name: ubuntu-storage
            - mountPath: /tmp/ssh
              name: ssh-key-volume
          restartPolicy: OnFailure
          volumes:
          - name: ubuntu-storage
            persistentVolumeClaim:
              claimName: pv-save-apache01
          - name: ssh-key-volume
            secret:
              secretName: ssh-key-secret
              items:
              - key: ssh-privatekey
                path: id_rsa
              - key: ssh-publickey
                path: id_rsa.pub
              - key: ssh-knowhosts
                path: known_hosts