apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu-container
    image: killiankopp/k8s-pod-workstation:latest
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 22
      name: ssh
  restartPolicy: Always