apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu-container
    image: killiankopp/k8s-pod-workstation:latest
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 22
      name: ssh
    volumeMounts:
    - mountPath: /mnt/save-apache01
      name: ubuntu-storage
  volumes:
  - name: ubuntu-storage
    persistentVolumeClaim:
      claimName: pv-save-apache01
  restartPolicy: Always