apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-save-apache01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-cinder-classic